# --------------------
# -- Debugging Code --#breakpoint output , errorالنقطه الحمره الي باجي عنداول سطر كود و بضغط عليه بيبينلي ال
# --------------------

my_list = [1, 2, 3]

my_dictionary = {"Name": "Osama", "Age": 36, "Country": "Egypt"}

for num in my_list:

  print(num)

for key, value in my_dictionary.items():

  print(f"{key} => {value}")

def function_one_one():

  print("Hello From Function One")

function_one_one()