# -----------------------------------------------
# -- Installing And Use Pylint For Better Code --#بيخليك تمشي علي النظام السليم للكود
# -----------------------------------------------#STTLE OF CODE بتاع الشركات العالميه

"""
This is My Module
To Create Function
To Say Hello
"""

def say_hello(name):
  '''This Function Only Say Hello To Someone'''
  msg = "Hello"
  return f"{msg} {name}"

say_hello("Ahmed")
#بيقيم الكود
#لازم علشاناعمله باجي في tirminal وبقوله "pip install pylint"